FROM ubuntu:bionic
WORKDIR /root
CMD /bin/bash

RUN apt-get update \
    && apt-get install -y \
        python3-pip \
        gnuplot \
    && pip3 install grip pytest numpy \
    && apt-get clean

RUN apt-get update \
    && apt-get install -y \
        ruby-full \
    && gem install \
        rake\
        package_cloud \
    && apt-get clean
